<?xml version="1.0" encoding="UTF-8"?>
<?eclipse version="3.4"?>
<plugin>
   <extension
         point="org.eclipse.ui.views.properties.tabbed.propertySections">
      <propertySections
            contributorId="com.tibco.xpd.processeditor.xpdl2.propertyContributor">
         <propertySection
               class="com.tibco.xpd.subprocess.datamapper.SubProcessDataMapperInSection"
               enablesFor="1"
               filter="com.tibco.xpd.subprocess.datamapper.SubProcessDataMapperInSection"
               id="com.tibco.xpd.subprocess.datamapper.in"
               tab="com.tibco.xpd.processeditor.propertyTabs.SubprocParameterMapperIn">
         </propertySection>
         <propertySection
               class="com.tibco.xpd.subprocess.datamapper.SubProcessDataMapperOutSection"
               enablesFor="1"
               filter="com.tibco.xpd.subprocess.datamapper.SubProcessDataMapperOutSection"
               id="com.tibco.xpd.subprocess.datamapper.out"
               tab="com.tibco.xpd.processeditor.propertyTabs.SubprocParameterMapperOut">
         </propertySection>
          <propertySection
               class="com.tibco.xpd.catcherror.datamapper.section.CatchAllErrorDataMapperSection"
               enablesFor="1"
               filter="com.tibco.xpd.catcherror.datamapper.section.CatchAllErrorDataMapperSection"
               id="com.tibco.xpd.catcherror.datamapper.catchall"
               tab="com.tibco.xpd.processeditor.propertyTabs.CatchErrorEventMapperOut">
         </propertySection>
        <propertySection
               class="com.tibco.xpd.subprocess.datamapper.catcherror.section.SubprocessCatchErrorDataMapperSection"
               enablesFor="1"
               filter="com.tibco.xpd.subprocess.datamapper.catcherror.section.SubprocessCatchErrorDataMapperSection"
               id="com.tibco.xpd.catcherror.datamapper.catchSpecific"
               tab="com.tibco.xpd.processeditor.propertyTabs.CatchErrorEventMapperOut">
         </propertySection>
         <propertySection
               class="com.tibco.xpd.globaldataservice.datamapper.GlobalDataErrorDataMapperMapFromErrorSection"
               enablesFor="1"
               filter="com.tibco.xpd.globaldataservice.datamapper.GlobalDataErrorDataMapperMapFromErrorSectionFilter"
               id="com.tibco.xpd.globaldataservice.CatchErrorDataMapperOut"
               tab="com.tibco.xpd.processeditor.propertyTabs.CatchErrorEventMapperOut">
         </propertySection>           
      </propertySections>
   </extension>
   <extension
         point="com.tibco.xpd.script.ui.scriptGrammarDestinationBinding">
      <destination
            destinationId="bpmn1">
                     <scriptContextGrammarBinding
               scriptContextReference="SubProcessTask">
            <defaultGrammar
                  id="DataMapper"
                  resourceMarkerAnnotationProvider="com.tibco.xpd.process.js.model.script.JavaScriptResourceMarkerAnnotationModelProvider"
                  scriptInfoProvider="com.tibco.xpd.process.js.model.script.ProcessJavaScriptInfoProvider">
            </defaultGrammar>
            <grammar
                  id="JavaScript"
                  resourceMarkerAnnotationProvider="com.tibco.xpd.process.js.model.script.JavaScriptResourceMarkerAnnotationModelProvider"
                  scriptInfoProvider="com.tibco.xpd.process.js.model.script.ProcessJavaScriptInfoProvider">
            </grammar>
         </scriptContextGrammarBinding>
            
      </destination>
   </extension>
   <extension
         point="com.tibco.xpd.datamapper.DataMapperContentContribution">
      <mapperContentContributor
            applicableContext="ProcessToSubProcess"
            applyToMapperRHS="false"
            mapperContribution="com.tibco.xpd.process.datamapper.common.ActivityInterfaceDataMapperContentContributor"
            priority="2">
      </mapperContentContributor>
       <mapperContentContributor
            applicableContext="ProcessToSubProcess"
            applyToMapperRHS="true"
            mapperContribution="com.tibco.xpd.subprocess.datamapper.SubProcessDataMapperInContentContributor"
            priority="3">
      </mapperContentContributor>
      <mapperContentContributor
            applicableContext="SubProcessToProcess"
            applyToMapperRHS="true"
            mapperContribution="com.tibco.xpd.process.datamapper.common.ActivityInterfaceDataMapperContentContributor"
            priority="2">
      </mapperContentContributor>
      <mapperContentContributor
            applicableContext="SubProcessToProcess"
            applyToMapperRHS="false"
            mapperContribution="com.tibco.xpd.subprocess.datamapper.SubProcessDataMapperOutContentContributor"
            priority="3">
      </mapperContentContributor>
      <mapperContentContributor
            applicableContext="CatchSubProcessError"
            applyToMapperRHS="true"
            mapperContribution="com.tibco.xpd.process.datamapper.common.ActivityInterfaceDataMapperContentContributor"
            priority="2">
      </mapperContentContributor>
      <mapperContentContributor
            applicableContext="CatchSubProcessError"
            applyToMapperRHS="false"
            mapperContribution="com.tibco.xpd.subprocess.datamapper.catcherror.CatchCSPErrorParamDataMapperContentContributor"
            priority="3">
      </mapperContentContributor>
       <mapperContentContributor
            applicableContext="CatchSubProcessError"
            applyToMapperRHS="false"
            mapperContribution="com.tibco.xpd.subprocess.datamapper.catcherror.CatchCSPErrorSubProcParamDataMapperContentContributor"
            priority="3">
      </mapperContentContributor>
      <mapperContentContributor
            applicableContext="GDFaultCatch"
            applyToMapperRHS="false"
            mapperContribution="com.tibco.xpd.globaldataservice.datamapper.GlobalDataCatchFaultDataMapperContentContributor"
            priority="3">
      </mapperContentContributor>
            <mapperContentContributor
            applicableContext="GDFaultCatch"
            applyToMapperRHS="true"
            mapperContribution="com.tibco.xpd.process.datamapper.common.ActivityInterfaceDataMapperContentContributor"
            priority="2">
      </mapperContentContributor>
   </extension>
   <extension
         point="com.tibco.xpd.datamapper.DataMapperContentContribution">
      <mapperContentContributor
            applicableContext="CatchAll"
            applyToMapperRHS="true"
            mapperContribution="com.tibco.xpd.process.datamapper.common.ActivityInterfaceDataMapperContentContributor"
            priority="2">
      </mapperContentContributor>
      <mapperContentContributor
            applicableContext="CatchAll"
            applyToMapperRHS="false"
            mapperContribution="com.tibco.xpd.catcherror.datamapper.CatchAllDataMapperContentContributor"
            priority="3">
      </mapperContentContributor>
    </extension>
   <extension
         point="com.tibco.xpd.process.datamapper.dataReferenceContextProvider">
      <provider
            providerClass="com.tibco.xpd.subprocess.datamapper.SubProcessDataReferenceContextProvider">
      </provider>
      <provider
            providerClass="com.tibco.xpd.catcherror.datamapper.CatchErrorDataReferenceContextProvider">
      </provider>
      <provider
            providerClass="com.tibco.xpd.globaldataservice.datamapper.GlobalDataCatchErrorDataReferenceContextProvider">
      </provider>
   </extension>
</plugin>
